version: '3.8'

services:
  hekate-api:
    build: .
    container_name: hekate-api-service
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - SPRING_APPLICATION_NAME=Hekate
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/ecommerceHekate?useSSL=false&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL8Dialect
      - LOGGING_LEVEL_ORG_HIBERNATE_SQL=DEBUG

  db:
    image: mysql:8.0
    container_name: hekate-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: ecommerceHekate
    ports:
      - "3306:3306"
    volumes:
      - hekate-db-data:/var/lib/mysql

volumes:
  hekate-db-data: